### ISSUE TITLE
Possible git.openstack.org URL change

### ISSUE THREAD

**Issue by Apsu** [rcbops/ansible-lxc-rpc#188]
https://git.openstack.org/openstack/nova -- for a nova example -- seems to no longer be the place to do the things. https://git.openstack.org/cgit/openstack/nova/ is the new hotness these days. We should probably fix where we point.

**Comment by cloudnull** [comment]
There have been no end of issues with "git.openstack.org". At this time Im in favor of this change if it improves the deployment process. Additionally, I think that we may want to swap github and git.openstack uri's in the `git_repo` and `git_fallback_repo` because of general stability issues.

Related: https://github.com/rcbops/ansible-lxc-rpc/pull/163

**Comment by Apsu** [comment]
+1
