### ISSUE TITLE
Repo generator should be able to generate config containing all available packages

### ISSUE THREAD

**Issue by mancdaz** [rcbops/ansible-lxc-rpc#33]
<a href="https://github.com/hughsaunders"><img src="https://avatars.githubusercontent.com/u/253506?v=2" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [hughsaunders](https://github.com/hughsaunders)**
_Tuesday Aug 26, 2014 at 14:49 GMT_
_Originally opened as https://github.com/rcbops/ansible-lxc-rpc-orig/issues/470_

---

This will help with bootstrapping the frozen repo process - get a list of all available packages and generate config. 

Additionally, it would be useful to have a command to check if an any new packages are available (perhaps an option to the update check).

**Comment by cloudnull** [comment]
In the CDC wip, pr#51, all packages have been moved into variables within the vars/repo_packages directory. This should allow us to, at a high level, programmatically scan the files in that directory for the repositories needed as well as the packages. However this PR is massive and blocked due to the state of our current repo.

**Comment by hughsaunders** [comment]
fixed in 33b0dbd1f5072662bd7ee8ac17610a709af5bdb9
