### ISSUE TITLE
RPC Support SSH keys on neutron_agents_container

### ISSUE THREAD

**Issue by Bumblebee-Man** [rcbops/ansible-lxc-rpc#390]
In order to log into a server we must ssh into the neutron_agents_container to utilize the network namespace. Right now we manually copying over the ssh keys from utility_container. Would be great to have this automatically set-up.

**Comment by cloudnull** [comment]
While I understand the use case of adding the support keys to the neutron agents containers as a means of getting access to a VM to troubleshooting networking issues from a network namespace I question the validity of these tests using an image that would require an SSH key to begin with. If the whole intention of this change is to allow easier access to an instance via ssh through a namespace I would assume that it would be faster and simpler to use a Cirros image which permits password authentication by default. If all of the namespace tests pass the support tech can move back to the utility container, assign a floating IP and test for connectivity. The only real value of the support SSH key pair is to ensure that metadata is being properly passed to a VM which can all be done using a light weight Cirros image and console logging.

I don't know if we are on the right track by promoting a habit of troubleshooting network issues with non-test image types while working within a namespace. This entire act has little to no effect on how a customer would interact with a given VM and has a potential for exacerbated security issues.  With the support SSH key only on the utility containers we have a single place to manage a system generate key pair in a location we expect users to be in and out of.

All this said, I'd like to get some feedback and more details on this change from anyone else that my have an opinion on the matter.

**Comment by odyssey4me** [comment]
The trouble with taking the approach of only using a cirros test image is that it'll take support much longer to get issues resolved. It also creates situations where a customer has a problem, support tests with cirros and it works out fine, then support sits in a quandry because there isn't a good reason why the customer's image didn't work as it was supposed to.

Perhaps a better approach would be to have support defined 'officially supported' images, and for those images we allow access via a limited set of public keys (perhaps the container becomes a bastion of some sort so we only have to deploy one public key to the instance)?

No idea whether this is practical - it's just a shot in the dark.

**Comment by Apsu** [comment]
Jus to get some clarification, when you say "log into the server", are we talking about logging into Customer instances as a form of guest support? Or merely testing customer images that are launched with our support keypair? Or merely testing that networking/DHCP/metadata/SSH are working? Or testing customer images are working in some other sense?

We need details on what exactly is attempting to be done here so we can discuss the proper way to A) deploy it, B) manage it and C) secure it.

**Comment by mancdaz** [comment]
@Bumblebee-man
