### ISSUE TITLE
Galera Limits not set

### ISSUE THREAD

**Issue by bjoernt** [rcbops/ansible-lxc-rpc#410]
Galera container running still with os file limit of 1k although 65K was configured in mariadb, that need to be fixed by using limits.conf. I saw in 9.0.1 this limit was set to 16K, I personally would set it to 128K so the system has more file handles available than actually mariadb allows

**Comment by claco** [comment]
@BjoernT Can you create other issues for the mysql connections limits so we can track that in a separate change. Thanks!

**Comment by bjoernt** [comment]
Sure I'll do that right away

**Comment by cloudnull** [comment]
The open file limits have been updated in master, stable/icehouse, and proposed/juno.

Set limits.conf files:
- https://github.com/rcbops/ansible-lxc-rpc/blob/proposed/juno/rpc_deployment/roles/galera_common/templates/limits.conf
- https://github.com/rcbops/ansible-lxc-rpc/blob/stable/icehouse/rpc_deployment/roles/galera_common/templates/limits.conf

This has been set per the performance tuning documentation as provided by the folks at MariaDB.  I'd be reluctant to set the limits on all possible open files to more than > 32K especially since this is a container living on a host with > 22 other containers.

This change modifies the max-connections value "https://github.com/rcbops/ansible-lxc-rpc/pull/444" which now provides for an override but also computes sane values based on the nodes galera is running on.

**Comment by bjoernt** [comment]
I'm ok with a limit < 32K but then we should reduce open-files-limit to 16K or so in mariadb. It makes no sense to run this still with 65K if the system only allows 32K
