### ISSUE TITLE
Syncing /etc/rpc_deploy and /opt/ansible-lxc-rpc across infrastructure nodes?

### ISSUE THREAD

**Issue by cfarquhar** [rcbops/ansible-lxc-rpc#453]
Can we set up a cron job on Infra01 that archives /etc/rpc_deploy and /opt/ansible-lxc-rpc on the other infrastructure nodes?  I would like some degree of redundancy in CDC environments where we don't control backups.  I'm open to discussing better alternatives.

**Comment by claco** [comment]
@cfarquhar In the past, the hesitation has been around what happens if someone makes a change on infra2, then goes back to intra1, etc. Seems to me like, the last node to sync wins. Maybe an ansible play that is always run manually is better than a cron. Even when we do control backups, you're out of luck until the restore is performed and/or the infra1 node is alive again, which could be a non desirable amount of time.

**Comment by mancdaz** [comment]
@claco @cfarquhar I think there's easy mitigation for the 'what if someone does something on node2':
- always do things on node1
- sync to a place on node2/3/x that is not the place you would expect to deploy from eg: /root/rpc_conf_backups
- one way sync from node1 > nodex. node1 always wins in terms of it's config being the master
- always do things on node1

**Comment by claco** [comment]
To be clear, I'm 100% in favor if us doing this.

"sync to a place on node2/3/x that is not the place you would expect to deploy from eg: /root/rpc_conf_backups" might defeat the purpose. If node1 is dead, and waiting on resurrection, I'd thing people would want to, or need to log into node2/3, and just be able to run ansible w/o having to shuffle things out of a backup location.

**Comment by cfarquhar** [comment]
@claco This works for me.  Thanks!

**Comment by mancdaz** [comment]
@cfarquhar @claco I'm not clear on what we agreed to? sync to /etc/rpc_deploy, or some other location on the other nodes?
