### ISSUE TITLE
Allow for lowering of MySQL connection timeout

### ISSUE THREAD

**Issue by Bumblebee-Man** [rcbops/ansible-lxc-rpc#457]
We've seen a couple "too many connections" errors in log files. After reviewing the number of MySQL connections it's pretty common to average around 380 connections at any given time. With light load we've seen a cluster go from 380 connections to 500 connections. To help get around this issue we've implemented #454. 

Although #454 helped to resolve the "too many connections" issue we feel there is a larger issue of connections not timing out. The longest MySQL connection we've seen is >2500 seconds. 

Would be great if an option can be added to /etc/rpc_deploy/user_variables.yml to allow a user to define the 'wait_timeout' variable for MariaDB. This variable should default to 3600 seconds.

**Comment by mancdaz** [comment]
@Bumblebee-Man what LB are you using? We did make a change to the haproxy galera backend because of some other timeout issues we were seeing during dev deployments:

https://github.com/rcbops/ansible-lxc-rpc/blob/master/rpc_deployment/vars/config_vars/haproxy_config.yml#L22-L23

May be related if you're using haproxy?

**Comment by Bumblebee-Man** [comment]
@mancdaz using F5. No Haproxy in the environment.

**Comment by cloudnull** [comment]
The option "galera_wait_timeout" has been added to the example user_variables file and can be set to further tune galera.
